### PR TITLE
Bugfix/37 runs program as root

### LINKED ISSUE #37: [BUG] Launch Joule Profiler with sudo runs program with root privileges
### Description

When Joule Profiler is launched with root privileges (using powercap or with perf_event paranoid level set to more than zero), than the profiled program inherit from it, thus creating a major security issue.

### Steps to Reproduce

Run Joule Profiler with sudo with a command requiring root privileges, you'll see that the profile program has root privileges.

```
sudo joule-profiler phases -- {command requiring sudo}
```

### Expected Behavior

The profiled program should not inherit root privileges from Joule Profiler, it must be executed with the current user id unless the user explicitly tell that he wants to execute it with root privileges.
A flag `--root` could be added to the CLI options, or we could parse the profiled command to execute it with root privileges if it starts with "sudo".

### Version

v1.0.1

### PR DESCRIPTION
**Pull request by FrancoisGib**
When Joule Profiler was running with root privileges, then the profiled command was also running as root, thus adding a major security issue.

This pull request fixes this issue by adding a `--use-root` flag to the CLI and a `use_root` field in the profiling configuration.

If this flag is set to true and Joule Profiler is executed as root, then the profiled command is still executed as root, but if the flag is set to false, then the effective user id is retrieved and the program is executed as a regular user.

If the profiled command is preceded by `sudo`, then the flag is not required because it is already executing as root user.

The main purpose is that if a user needs to run Joule Profiler as root, the profiled command is executed as regular user, unless specified.

### CODE REVIEW

File: cli/src/commands/phases.rs [hunk 1]
```diff
@@ -33,4 +33,8 @@ pub struct PhasesArgs {
     /// Rapl polling frequency in second.
     #[arg(long = "rapl-polling")]
     pub rapl_polling: Option<f64>,
+
+    /// Executes the profiled command with root privileges if true and Joule Profiler is launched as root.
+    #[arg(long = "root")]
```
Comment (jwoirhaye) [inline cli/src/commands/phases.rs]: use-root is better for the param name

**Review by jwoirhaye — CHANGES_REQUESTED** [review]

File: cli/src/commands/phases.rs (hunk 1 above)
Comment (FrancoisGib) [reply cli/src/commands/phases.rs]: done
